services:
  postgres:
    container_name: postgres
    image: postgres
    init: true
    # build: .
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      - PGUSER=postgres
      - DOPPLER_TOKEN
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_CRYPTOKEY
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRESQL_USERNAME_CONNECTION_LIMIT=9001
      - POSTGRESQL_POSTGRES_CONNECTION_LIMIT=9001
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - default
      - predictive

  adminer:
    container_name: adminer
    image: adminer
    volumes:
      - ./adminer.css:/var/www/html/adminer.css
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: unless-stopped

networks:
  predictive:
    external: true
